[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
# (Optional) Text in landing page button
LANDING_BUTTON = "Click to jump in"
# (Optional) Site description on landing page
LANDING_DESCRIPTION = "I have nothing"
# (REQUIRED) The Markdown page linked to landing page button (e.g. put home for ./home.md)
LANDING_PAGE = "home"
# (Optional) Site title on landing page
LANDING_TITLE = "Welcome!"
PYTHON_VERSION = "3.8"
# (REQUIRED) Site repo URL
REPO_URL = "https://www.github.com/BareDesigns/Obsidian_Backup"
# (Optional) Site title in navbar
SITE_TITLE = "Jon's 🧠"
# (Optional) Site title in browser tab (leave blank to use SITE_TITLE)
SITE_TITLE_TAB = "2nd Brain"
# (REQUIRED) Netlify site URL
SITE_URL = "https://notes.baredesigns.xyz"
# (Optional) Site Timezone
TIMEZONE = "North America/Central Daylight Time"
ZOLA_VERSION = "0.15.2"
# (Optional, defaul title) How to sort notes inside each section on the right sidebar ("date" or "title"). Subsections on side bar are sorted by title, the sort order cannot be changed.
SORT_BY = "title"
# (Optional) Google Analytics Measurement ID
GANALYTICS = ""
# (Optional, default true) Slugify URLs. Put "" to disable.
SLUGIFY = ""
# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.
HOME_GRAPH = "y"
# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.
PAGE_GRAPH = "y"
